### ISSUE TITLE
TXT record not set

### ISSUE THREAD

**Issue by ruudboon** [adferrand/docker-letsencrypt-dns#36]
I would like to setup signing with transip as DNS Provider. Unfortunately I get the following error:
```
2018-12-18 21:10:49,127:ERROR:certbot.hooks:Error output from cleanup.sh:
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 98, in main
    results = client.execute()
  File "/usr/local/lib/python3.7/site-packages/lexicon/client.py", line 56, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python3.7/site-packages/lexicon/providers/transip.py", line 64, in authenticate
    self.client.get_info(domain)
  File "/usr/local/lib/python3.7/site-packages/transip/service/domain.py", line 56, in get_info
    cookie = self.build_cookie(mode=MODE_RO, method='getInfo', parameters=[domain_name])
  File "/usr/local/lib/python3.7/site-packages/transip/client.py", line 155, in build_cookie
    signature = self._sign(message_to_sign)
  File "/usr/local/lib/python3.7/site-packages/transip/client.py", line 89, in _sign
    raise RuntimeError('The private key does not exist.')
RuntimeError: The private key does not exist.
```

**Comment by ruudboon** [comment]
Looks like a lexicon issue
