### ISSUE TITLE
babel not found

### ISSUE THREAD

**Issue by Moeplhausen** [adferrand/docker-letsencrypt-dns#4]
While testing, letsencrypt suddenly stopped working. I think something changed while I was testing on some lower layer though since I am getting the following error:

```
letsencrypt-dns_1  | Hook command "/var/lib/letsencrypt/hooks/authenticator.sh" returned error code 1
letsencrypt-dns_1  | Error output from authenticator.sh:
letsencrypt-dns_1  | Traceback (most recent call last):
letsencrypt-dns_1  |   File "/usr/local/bin/lexicon", line 11, in <module>
letsencrypt-dns_1  |     sys.exit(main())
letsencrypt-dns_1  |   File "/usr/local/lib/python3.6/site-packages/lexicon/__main__.py", line 66, in main
letsencrypt-dns_1  |     parsed_args = MainParser().parse_args()
letsencrypt-dns_1  |   File "/usr/local/lib/python3.6/site-packages/lexicon/__main__.py", line 54, in MainParser
letsencrypt-dns_1  |     provider_module = importlib.import_module('lexicon.providers.' + provider)
letsencrypt-dns_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
letsencrypt-dns_1  |     return _bootstrap._gcd_import(name[level:], package, level)
letsencrypt-dns_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
letsencrypt-dns_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
letsencrypt-dns_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
letsencrypt-dns_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
letsencrypt-dns_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
letsencrypt-dns_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
letsencrypt-dns_1  |   File "/usr/local/lib/python3.6/site-packages/lexicon/providers/dnsmadeeasy.py", line 10, in <module>
letsencrypt-dns_1  |     from babel.dates import format_date, format_datetime, format_time
letsencrypt-dns_1  | ModuleNotFoundError: No module named 'babel'
```

Unless I messed up somewhere, I think this is something that you can hopefully fix, please?

**Comment by adferrand** [comment]
Ouch. Seems that the new version of Lexicon does not declare all its dependencies. I am investigating ...

**Comment by adferrand** [comment]
Ok. An optional dependency (babel) is not so optional, as it breaks lexicon if not present. 
I corrected that: patched version 1.4.2 of my container is currently building on Docker Hub.

Thank you a lot for your report !

**Comment by Moeplhausen** [comment]
Thanks, it works now.

**Comment by adferrand** [comment]
Resolution confirmed, I close the issue.
