### ISSUE TITLE
DNS TXT-record cleanup stage fails

### ISSUE THREAD

**Issue by Akkarine** [adferrand/docker-letsencrypt-dns#58]
DNS-01 challenge, Yandex DNS provider. TXT-record created, but not deleted.

For fail at certificate creation I blame slow DNS replication (looks like 70 seconds not enough).

I ran the command:

```shell
sudo docker run \
    --name letsencrypt-dns \
    --volume /srv/letsencrypt-dns:/etc/letsencrypt \
    --env 'LETSENCRYPT_USER_MAIL=*******' \
    --env 'LEXICON_PROVIDER=yandex' \
    --env 'LEXICON_SLEEP_TIME=70' \
    --env 'LEXICON_PROVIDER_OPTIONS=--auth-token=********************' \
    --env 'LETSENCRYPT_STAGING=true' \
    adferrand/letsencrypt-dns:latest
```

Output:
```
2019-08-17 16:51:42 circus[1] [INFO] Starting master on pid 1
2019-08-17 16:51:42 circus[1] [INFO] Arbiter now waiting for commands
2019-08-17 16:51:42 circus[1] [INFO] crond started
2019-08-17 16:51:42 circus[1] [INFO] watch-domains started
2019-08-17 16:51:42 [18] | #### Registering Let's Encrypt account if needed ####
2019-08-17 16:51:43 [18] | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2019-08-17 16:51:44 [18] | IMPORTANT NOTES:
2019-08-17 16:51:44 [18] |  - Your account credentials have been saved in your Certbot
2019-08-17 16:51:44 [18] |    configuration directory at /etc/letsencrypt. You should make a
2019-08-17 16:51:44 [18] |    secure backup of this folder now. This configuration directory will
2019-08-17 16:51:44 [18] |    also contain certificates and private keys obtained by Certbot so
2019-08-17 16:51:44 [18] |    making regular backups of this folder is ideal.
2019-08-17 16:51:44 [18] | #### Clean autorestart/autocmd jobs
2019-08-17 16:51:44 [18] | #### Creating missing certificates if needed (~1min for each) ####
2019-08-17 16:51:44 [18] | >>> Creating a certificate for domain(s): -d *****************
2019-08-17 16:51:45 [18] | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2019-08-17 16:51:45 [18] | Plugins selected: Authenticator manual, Installer None
2019-08-17 16:51:45 [18] | Obtaining a new certificate
2019-08-17 16:51:47 [18] | Performing the following challenges:
2019-08-17 16:51:47 [18] | dns-01 challenge for ***********
2019-08-17 16:51:47 [18] | Running manual-auth-hook command: /var/lib/letsencrypt/hooks/authenticator.sh
2019-08-17 16:53:00 [18] | Output from manual-auth-hook command authenticator.sh:
2019-08-17 16:53:00 [18] | RESULT
2019-08-17 16:53:00 [18] | ------
2019-08-17 16:53:00 [18] | True
2019-08-17 16:55:24 [18] | Waiting for verification...
2019-08-17 16:55:27 [18] | Challenge failed for domain ************
2019-08-17 16:55:30 [18] | dns-01 challenge for **********
2019-08-17 16:55:30 [18] | Cleaning up challenges
2019-08-17 16:55:30 [18] | Running manual-cleanup-hook command: /var/lib/letsencrypt/hooks/cleanup.sh
2019-08-17 16:55:31 [18] | manual-cleanup-hook command "/var/lib/letsencrypt/hooks/cleanup.sh" returned error code 1
2019-08-17 16:55:31 [18] | Error output from manual-cleanup-hook command cleanup.sh:
2019-08-17 16:55:31 [18] | Traceback (most recent call last):
2019-08-17 16:55:31 [18] |   File "/usr/local/bin/lexicon", line 10, in <module>
2019-08-17 16:55:31 [18] |     sys.exit(main())
2019-08-17 16:55:31 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 117, in main
2019-08-17 16:55:31 [18] |     results = client.execute()
2019-08-17 16:55:31 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/client.py", line 87, in execute
2019-08-17 16:55:31 [18] |     return self.provider.delete_record(identifier, record_type, name, content)
2019-08-17 16:55:31 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/base.py", line 118, in delete_record
2019-08-17 16:55:31 [18] |     return self._delete_record(identifier=identifier, rtype=rtype, name=name, content=content)
2019-08-17 16:55:31 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/yandex.py", line 120, in _delete_record
2019-08-17 16:55:31 [18] |     records = self._list_records(rtype, name, content)
2019-08-17 16:55:31 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/yandex.py", line 76, in _list_records
2019-08-17 16:55:32 [18] |     'content': record['content'],
2019-08-17 16:55:32 [18] | KeyError: 'content'
2019-08-17 16:55:35 [18] | Some challenges have failed.
2019-08-17 16:55:35 [18] | IMPORTANT NOTES:
2019-08-17 16:55:35 [18] |  - The following errors were reported by the server:
2019-08-17 16:55:35 [18] |    Domain: **********
2019-08-17 16:55:35 [18] |    Type:   unauthorized
2019-08-17 16:55:35 [18] |    Detail: No TXT record found at _acme-challenge.**********
2019-08-17 16:55:35 [18] | md5sum: can't open '/etc/letsencrypt/live/*****/cert.pem': No such file or directory
2019-08-17 16:55:35 [18] | ### Revoke and delete certificates if needed ####
2019-08-17 16:55:35 [18] | ### Reloading circusd configuration ###
2019-08-17 16:55:35 [18] | ok
2019-08-17 17:00:30 circus[1] [INFO] Got signal SIG_WINCH
```

**Comment by adferrand** [comment]
Interesting. The error is not in my Docker, but in Lexicon. In some pathological situations a given Yandex DNS record has no content, and it makes Lexicon fail.

This is an issue for Lexicon, but I am also one of its maintainer, so it will be fixed quite fast. 

However, I need your help, because I do not have credentials for Yandex, so I cannot check directly the fix I have in mind will work. 

Could you:
1) Start an instance of my Docker with proper credentials for Yandex (basically the same config that what you used here) 
2) Go into this instance `docker exec...`
3) Install an editor (like `apk install nano`)
4) Change, in `/usr/local/lib/python3.7/site-packages/lexicon/providers/yandex.py` the line 76 `'content': record['content'],` into `'content': record.get('content'),`
5) Issue a new certificate by editing `domains.conf`
6) Check that after the DNS propagation timeout, the cleanup script is not failing anymore?

If this is too much, I can provide you a prebuilt test version of my Docker with the correction asked in 4) to test directly.

**Comment by Akkarine** [comment]
Thank you for fast answer, @adferrand ! No problem, made this change. But I've already requested new certificates and due to long DNS-replication must wait 12 hours. After that I'll give feedback.

**Comment by Akkarine** [comment]
Unfortunately, fix didn't help.

```
$ sudo docker logs letsencrypt-dns
2019-08-17 17:28:43 circus[1] [INFO] Starting master on pid 1
2019-08-17 17:28:43 circus[1] [INFO] Arbiter now waiting for commands
2019-08-17 17:28:43 circus[1] [INFO] crond started
2019-08-17 17:28:43 circus[1] [INFO] watch-domains started
2019-08-17 17:28:43 [18] | #### Registering Let's Encrypt account if needed ####
2019-08-17 17:28:43 [18] | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2019-08-17 17:28:43 [18] | There is an existing account; registration of a duplicate account with this command is currently u                                    nsupported.
2019-08-17 17:28:43 [18] | #### Clean autorestart/autocmd jobs
2019-08-17 17:28:43 [18] | #### Creating missing certificates if needed (~1min for each) ####
2019-08-17 17:28:43 [18] | >>> Creating a certificate for domain(s): -d *.dev.********.ru -d *.infra.********.ru
2019-08-17 17:28:44 [18] | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
2019-08-17 17:28:44 [18] | Plugins selected: Authenticator manual, Installer None
2019-08-17 17:28:44 [18] | Obtaining a new certificate
2019-08-17 17:28:46 [18] | Performing the following challenges:
2019-08-17 17:28:46 [18] | dns-01 challenge for dev.********.ru
2019-08-17 17:28:46 [18] | dns-01 challenge for infra.********.ru
2019-08-17 17:28:46 [18] | Running manual-auth-hook command: /var/lib/letsencrypt/hooks/authenticator.sh
2019-08-18 01:12:00 [17] | Launch renew test
2019-08-18 01:12:00 [17] | Another instance of Certbot is already running.
2019-08-18 05:28:47 [18] | Output from manual-auth-hook command authenticator.sh:
2019-08-18 05:28:47 [18] | RESULT
2019-08-18 05:28:47 [18] | ------
2019-08-18 05:28:47 [18] | True
2019-08-18 05:28:47 [18] | Running manual-auth-hook command: /var/lib/letsencrypt/hooks/authenticator.sh
2019-08-18 13:12:00 [17] | Launch renew test
2019-08-18 13:12:01 [17] | Another instance of Certbot is already running.
2019-08-18 17:28:50 [18] | Output from manual-auth-hook command authenticator.sh:
2019-08-18 17:28:50 [18] | RESULT
2019-08-18 17:28:50 [18] | ------
2019-08-18 17:28:50 [18] | True
2019-08-18 17:28:50 [18] | Waiting for verification...
2019-08-18 17:28:58 [18] | Cleaning up challenges
2019-08-18 17:28:58 [18] | Running manual-cleanup-hook command: /var/lib/letsencrypt/hooks/cleanup.sh
2019-08-18 17:29:00 [18] | manual-cleanup-hook command "/var/lib/letsencrypt/hooks/cleanup.sh" returned error code 1
2019-08-18 17:29:00 [18] | Error output from manual-cleanup-hook command cleanup.sh:
2019-08-18 17:29:00 [18] | Traceback (most recent call last):
2019-08-18 17:29:00 [18] |   File "/usr/local/bin/lexicon", line 10, in <module>
2019-08-18 17:29:00 [18] |     sys.exit(main())
2019-08-18 17:29:00 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 117, in main
2019-08-18 17:29:00 [18] |     results = client.execute()
2019-08-18 17:29:00 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/client.py", line 87, in execute
2019-08-18 17:29:00 [18] |     return self.provider.delete_record(identifier, record_type, name, content)
2019-08-18 17:29:00 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/base.py", line 118, in delete_rec                                    ord
2019-08-18 17:29:00 [18] |     return self._delete_record(identifier=identifier, rtype=rtype, name=name, content=content)
2019-08-18 17:29:00 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/yandex.py", line 120, in _delete_                                    record
2019-08-18 17:29:00 [18] |     records = self._list_records(rtype, name, content)
2019-08-18 17:29:00 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/yandex.py", line 76, in _list_rec                                    ords
2019-08-18 17:29:00 [18] |     'content': record.get['content'],
2019-08-18 17:29:00 [18] | TypeError: 'builtin_function_or_method' object is not subscriptable
2019-08-18 17:29:00 [18] | Running manual-cleanup-hook command: /var/lib/letsencrypt/hooks/cleanup.sh
2019-08-18 17:29:02 [18] | manual-cleanup-hook command "/var/lib/letsencrypt/hooks/cleanup.sh" returned error code 1
2019-08-18 17:29:02 [18] | Error output from manual-cleanup-hook command cleanup.sh:
2019-08-18 17:29:02 [18] | Traceback (most recent call last):
2019-08-18 17:29:02 [18] |   File "/usr/local/bin/lexicon", line 10, in <module>
2019-08-18 17:29:02 [18] |     sys.exit(main())
2019-08-18 17:29:02 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 117, in main
2019-08-18 17:29:02 [18] |     results = client.execute()
2019-08-18 17:29:02 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/client.py", line 87, in execute
2019-08-18 17:29:02 [18] |     return self.provider.delete_record(identifier, record_type, name, content)
2019-08-18 17:29:02 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/base.py", line 118, in delete_rec                                    ord
2019-08-18 17:29:02 [18] |     return self._delete_record(identifier=identifier, rtype=rtype, name=name, content=content)
2019-08-18 17:29:02 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/yandex.py", line 120, in _delete_                                    record
2019-08-18 17:29:02 [18] |     records = self._list_records(rtype, name, content)
2019-08-18 17:29:02 [18] |   File "/usr/local/lib/python3.7/site-packages/lexicon/providers/yandex.py", line 76, in _list_rec                                    ords
2019-08-18 17:29:02 [18] |     'content': record.get['content'],
2019-08-18 17:29:02 [18] | TypeError: 'builtin_function_or_method' object is not subscriptable
2019-08-18 17:29:04 [18] | Non-standard path(s), might not work with crontab installed by your operating system package manag                                    er
2019-08-18 17:29:04 [18] | Running deploy-hook command: deploy-hook.sh
2019-08-18 17:29:04 [18] | IMPORTANT NOTES:
2019-08-18 17:29:04 [18] |  - Congratulations! Your certificate and chain have been saved at:
2019-08-18 17:29:04 [18] |    /etc/letsencrypt/live/dev.********.ru/fullchain.pem
2019-08-18 17:29:04 [18] |    Your key file has been saved at:
2019-08-18 17:29:04 [18] |    /etc/letsencrypt/live/dev.********.ru/privkey.pem
2019-08-18 17:29:04 [18] |    Your cert will expire on 2019-11-16. To obtain a new or tweaked
2019-08-18 17:29:04 [18] |    version of this certificate in the future, simply run certbot
2019-08-18 17:29:04 [18] |    again. To non-interactively renew *all* of your certificates, run
2019-08-18 17:29:04 [18] |    "certbot renew"
2019-08-18 17:29:04 [18] |  - If you like Certbot, please consider supporting our work by:
2019-08-18 17:29:04 [18] |    Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
2019-08-18 17:29:04 [18] |    Donating to EFF:                    https://eff.org/donate-le
2019-08-18 17:29:04 [18] | ### Revoke and delete certificates if needed ####
2019-08-18 17:29:04 [18] | ### Reloading circusd configuration ###
2019-08-18 17:29:05 [18] | ok
```

**Comment by Akkarine** [comment]
I've failed miserably when left square parenthesises. I'll retry again)

**Comment by Akkarine** [comment]
@adferrand Thank you, all worked!
![image](https://user-images.githubusercontent.com/13115270/63256119-76f91980-c266-11e9-8f5b-da154ae04a24.png)

**Comment by adferrand** [comment]
Thanks! I will make a new release of Lexicon, and integrate it here in the next days!

**Comment by adferrand** [comment]
Integrated in 2.17.0
