### ISSUE TITLE
DNS challenge with cloudflare issue

### ISSUE THREAD

**Issue by daniela-waranie** [adferrand/docker-letsencrypt-dns#78]
I am using your docker-compose file with latest letsencrypt-dns and cloudflare as dns provider.
When starting the docker container it get the following output:
```
letsencrypt-dns | 2020-03-09 16:18:55 circus[1] [INFO] Starting master on pid 1
letsencrypt-dns | 2020-03-09 16:18:55 circus[1] [INFO] Arbiter now waiting for commands
letsencrypt-dns | 2020-03-09 16:18:55 circus[1] [INFO] crond started
letsencrypt-dns | 2020-03-09 16:18:55 circus[1] [INFO] watch-domains started
letsencrypt-dns | 2020-03-09 16:18:55 [17] | #### Registering Let's Encrypt account if needed ####
letsencrypt-dns | 2020-03-09 16:18:55 [17] | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
letsencrypt-dns | 2020-03-09 16:18:55 [17] | There is an existing account; registration of a duplicate account with this command is currently unsupported.
letsencrypt-dns | 2020-03-09 16:18:55 [17] | #### Clean autorestart/autocmd jobs
letsencrypt-dns | 2020-03-09 16:18:55 [17] | #### Creating missing certificates if needed (~1min for each) ####
letsencrypt-dns | 2020-03-09 16:18:55 [17] | >>> Creating a certificate for domain(s): -d nextcloud.mydomain.de
letsencrypt-dns | 2020-03-09 16:18:56 [17] | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
letsencrypt-dns | 2020-03-09 16:18:56 [17] | Plugins selected: Authenticator manual, Installer None
letsencrypt-dns | 2020-03-09 16:18:57 [17] | Obtaining a new certificate
letsencrypt-dns | 2020-03-09 16:18:57 [17] | Performing the following challenges:
letsencrypt-dns | 2020-03-09 16:18:57 [17] | dns-01 challenge for nextcloud.mydomain.de
letsencrypt-dns | 2020-03-09 16:18:57 [17] | Running manual-auth-hook command: /var/lib/letsencrypt/hooks/authenticator.sh
letsencrypt-dns | 2020-03-09 16:18:59 [17] | manual-auth-hook command "/var/lib/letsencrypt/hooks/authenticator.sh" returned error code 1
letsencrypt-dns | 2020-03-09 16:18:59 [17] | Error output from manual-auth-hook command authenticator.sh:
letsencrypt-dns | 2020-03-09 16:18:59 [17] | Traceback (most recent call last):
letsencrypt-dns | 2020-03-09 16:18:59 [17] |   File "/usr/local/bin/lexicon", line 8, in <module>
letsencrypt-dns | 2020-03-09 16:18:59 [17] |     sys.exit(main())
letsencrypt-dns | 2020-03-09 16:18:59 [17] |   File "/usr/local/lib/python3.8/site-packages/lexicon/cli.py", line 117, in main
letsencrypt-dns | 2020-03-09 16:18:59 [17] |     results = client.execute()
letsencrypt-dns | 2020-03-09 16:18:59 [17] |   File "/usr/local/lib/python3.8/site-packages/lexicon/client.py", line 77, in execute
letsencrypt-dns | 2020-03-09 16:18:59 [17] |     self.provider.authenticate()
letsencrypt-dns | 2020-03-09 16:18:59 [17] |   File "/usr/local/lib/python3.8/site-packages/lexicon/providers/base.py", line 69, in authenticate
letsencrypt-dns | 2020-03-09 16:18:59 [17] |     return self._authenticate()
letsencrypt-dns | 2020-03-09 16:18:59 [17] |   File "/usr/local/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 32, in _authenticate
letsencrypt-dns | 2020-03-09 16:18:59 [17] |     payload = self._get('/zones', {
letsencrypt-dns | 2020-03-09 16:18:59 [17] |   File "/usr/local/lib/python3.8/site-packages/lexicon/providers/base.py", line 142, in _get
letsencrypt-dns | 2020-03-09 16:18:59 [17] |     return self._request('GET', url, query_params=query_params)
letsencrypt-dns | 2020-03-09 16:18:59 [17] |   File "/usr/local/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 146, in _request
letsencrypt-dns | 2020-03-09 16:18:59 [17] |     response.raise_for_status()
letsencrypt-dns | 2020-03-09 16:18:59 [17] |   File "/usr/local/lib/python3.8/site-packages/request
letsencrypt-dns | 2020-03-09 16:18:59 [17] | s/models.py", line 941, in raise_for_status
letsencrypt-dns | 2020-03-09 16:18:59 [17] |     raise HTTPError(http_error_msg, response=self)
letsencrypt-dns | 2020-03-09 16:18:59 [17] | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.de&status=active
letsencrypt-dns | 2020-03-09 16:18:59 [17] | Waiting for verification...
letsencrypt-dns | 2020-03-09 16:19:01 [17] | Challenge failed for domain nextcloud.mydomain.de
letsencrypt-dns | 2020-03-09 16:19:01 [17] | dns-01 challenge for nextcloud.mydomain.de
letsencrypt-dns | 2020-03-09 16:19:01 [17] | Cleaning up challenges
```

I am a little bit lost as this is the first time i use your docker container and also the first time i use cloudflare. I was creating the dns zone at cloudflare very minimalistic (just a A-record for main domain, but not an A-record for nextcloud.mydomain.de, as it should not be required when doing dns challenges). As far as i understand it is not even necessary that cloudflare is my active nameserver (at least not in this phase of the process: when trying to seed the TXT record) - at validation of dns challenge it is required to have cloudflare being the active nameserver for my domain.

At cloudflare this token has all possilble permissions (account + zone) across all resources (accounts and zones), so i think it is not a permission problem. 

I made cloudflare nameservers active for my domain (confirmed as active by cloudflare webUI) for a second run but still get the same issue (do i have to wait 24h to be sure, that letsencrypt CA is picking the right nameservers?).

Please help.

**Comment by daniela-waranie** [comment]
OMG! 

I filled the env variable `LEXICON_PROVIDER_OPTIONS` with `--auth-username=myname@mydomain.de --auth-token=cloudflare_api_token`, but instead of a cloudflare `API Token` i should use the cloudflare `API Key` for `--auth-token` - naming is a bit confusing here...

Now it works. Maybe we should improve the documentation with more examples (at least for all DNS providers with confusing naming).

**Comment by daniela-waranie** [comment]
A user-friendly error message instead of a stacktrace would be cool.

**Comment by adferrand** [comment]
Yes, I agree that the error is absolutely not obvious here. For cloudflare specifically pathological here, since you have global API keys, and more regular scoped API tokens. Here currently only global API keys are available, and an upstream issue is opened to get the scoped API tokens (https://github.com/AnalogJ/lexicon/pull/460).

Getting a nice error from my Docker is quite difficult however, since Lexicon is not sending an fine-grain error about what was wrong. I think it should be quite useful to raise an issue on the Lexicon GitHub project (and continue there, since I also one of the maintainers for this project).

I close the issue here, since the error is "technically" solved, but do not hesitate to give further feedbacks!

**Comment by yonathan9669** [comment]
Hello guys, I try to use the `Globar API Key` as @daniela-waranie suggested but it didn't work for me either. I've been using the docker image for this but I don't know if there is any difference between native and docker run.

### API Token log
```sh
dnsrobocert    | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
dnsrobocert    | Plugins selected: Authenticator manual, Installer None
dnsrobocert    | Obtaining a new certificate
dnsrobocert    | Performing the following challenges:
dnsrobocert    | dns-01 challenge for api.mydomain.com
dnsrobocert    | Running manual-auth-hook command: /usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"
dnsrobocert    | manual-auth-hook command "/usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"" returned error code 1
dnsrobocert    | Error output from manual-auth-hook command python3:
dnsrobocert    | 2020-04-19 23:23:51 0f6824afd7a9 __main__[73] ERROR Error while executing the `auth` hook:
dnsrobocert    | 2020-04-19 23:23:51 0f6824afd7a9 __main__[73] ERROR 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.com&status=active
dnsrobocert    | Traceback (most recent call last):
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 48, in main
dnsrobocert    |     globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 63, in auth
dnsrobocert    |     _txt_challenge(profile, token, domain, action="create")
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 174, in _txt_challenge
dnsrobocert    |     Client(lexicon_config).execute()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/client.py", line 77, in execute
dnsrobocert    |     self.provider.authenticate()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 69, in authenticate
dnsrobocert    |     return self._authenticate()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 32, in _authenticate
dnsrobocert    |     payload = self._get('/zones', {
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 142, in _get
dnsrobocert    |     return self._request('GET', url, query_params=query_params)
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 146, in _request
dnsrobocert    |     response.raise_for_status()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
dnsrobocert    |     raise HTTPError(http_error_msg, response=self)
dnsrobocert    | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.com&status=active
dnsrobocert    | 
dnsrobocert    | Waiting for verification...
dnsrobocert    | Challenge failed for domain api.mydomain.com
dnsrobocert    | dns-01 challenge for api.mydomain.com
dnsrobocert    | Cleaning up challenges
dnsrobocert    | Running manual-cleanup-hook command: /usr/bin/python3 -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"
dnsrobocert    | manual-cleanup-hook command "/usr/bin/python3 -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"" returned error code 1
dnsrobocert    | Error output from manual-cleanup-hook command python3:
dnsrobocert    | 2020-04-19 23:23:56 0f6824afd7a9 __main__[75] ERROR Error while executing the `cleanup` hook:
dnsrobocert    | 2020-04-19 23:23:56 0f6824afd7a9 __main__[75] ERROR 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.com&status=active
dnsrobocert    | Traceback (most recent call last):
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 48, in main
dnsrobocert    |     globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 125, in cleanup
dnsrobocert    |     _txt_challenge(profile, token, domain, action="delete")
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 174, in _txt_challenge
dnsrobocert    |     Client(lexicon_config).execute()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/client.py", line 77, in execute
dnsrobocert    |     self.provider.authenticate()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 69, in authenticate
dnsrobocert    |     return self._authenticate()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 32, in _authenticate
dnsrobocert    |     payload = self._get('/zones', {
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 142, in _get
dnsrobocert    |     return self._request('GET', url, query_params=query_params)
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 146, in _request
dnsrobocert    |     response.raise_for_status()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
dnsrobocert    |     raise HTTPError(http_error_msg, response=self)
dnsrobocert    | requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.com&status=active
dnsrobocert    | 
dnsrobocert    | Some challenges have failed.
dnsrobocert    | IMPORTANT NOTES:
dnsrobocert    |  - The following errors were reported by the server:
dnsrobocert    | 
dnsrobocert    |    Domain: api.mydomain.com
dnsrobocert    |    Type:   dns
dnsrobocert    |    Detail: DNS problem: NXDOMAIN looking up TXT for
dnsrobocert    |    _acme-challenge.api.mydomain.com - check that a DNS record
dnsrobocert    |    exists for this domain
dnsrobocert    | ----------
dnsrobocert    | 2020-04-19 23:23:56 0f6824afd7a9 dnsrobocert.core.main[1] ERROR An error occurred while processing certificate config `{'domains': ['api.mydomain.com'], 'profile': 'maestro_profile'}`:
dnsrobocert    | Command '['/usr/bin/python3', '-m', 'dnsrobocert.core.certbot', 'certonly', '-n', '--config-dir', '/etc/letsencrypt', '--work-dir', '/etc/letsencrypt/workdir', '--logs-dir', '/etc/letsencrypt/logs', '--manual', '--preferred-challenges=dns', '--manual-auth-hook', '/usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"', '--manual-cleanup-hook', '/usr/bin/python3 -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"', '--manual-public-ip-logging-ok', '--expand', '--deploy-hook', '/usr/bin/python3 -m dnsrobocert.core.hooks -t deploy -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"', '--server', 'https://acme-staging-v02.api.letsencrypt.org/directory', '--cert-name', 'api.mydomain.com', '-d', 'api.mydomain.com']' returned non-zero exit status 1.
dnsrobocert    | 2020-04-19 23:23:56 0f6824afd7a9 dnsrobocert.core.main[1] INFO Revoke and delete certificates if needed
```

### Global API Key log
```sh
dnsrobocert    | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
dnsrobocert    | Plugins selected: Authenticator manual, Installer None
dnsrobocert    | Obtaining a new certificate
dnsrobocert    | Performing the following challenges:
dnsrobocert    | dns-01 challenge for api.mydomain.com
dnsrobocert    | Running manual-auth-hook command: /usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"
dnsrobocert    | manual-auth-hook command "/usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"" returned error code 1
dnsrobocert    | Error output from manual-auth-hook command python3:
dnsrobocert    | 2020-04-19 23:30:44 0f6824afd7a9 __main__[81] ERROR Error while executing the `auth` hook:
dnsrobocert    | 2020-04-19 23:30:44 0f6824afd7a9 __main__[81] ERROR 403 Client Error: Forbidden for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.com&status=active
dnsrobocert    | Traceback (most recent call last):
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 48, in main
dnsrobocert    |     globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 63, in auth
dnsrobocert    |     _txt_challenge(profile, token, domain, action="create")
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 174, in _txt_challenge
dnsrobocert    |     Client(lexicon_config).execute()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/client.py", line 77, in execute
dnsrobocert    |     self.provider.authenticate()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 69, in authenticate
dnsrobocert    |     return self._authenticate()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 32, in _authenticate
dnsrobocert    |     payload = self._get('/zones', {
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 142, in _get
dnsrobocert    |     return self._request('GET', url, query_params=query_params)
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 146, in _request
dnsrobocert    |     response.raise_for_status()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
dnsrobocert    |     raise HTTPError(http_error_msg, response=self)
dnsrobocert    | requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.com&status=active
dnsrobocert    | 
dnsrobocert    | Waiting for verification...
dnsrobocert    | Challenge failed for domain api.mydomain.com
dnsrobocert    | dns-01 challenge for api.mydomain.com
dnsrobocert    | Cleaning up challenges
dnsrobocert    | Running manual-cleanup-hook command: /usr/bin/python3 -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"
dnsrobocert    | manual-cleanup-hook command "/usr/bin/python3 -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"" returned error code 1
dnsrobocert    | Error output from manual-cleanup-hook command python3:
dnsrobocert    | 2020-04-19 23:30:50 0f6824afd7a9 __main__[83] ERROR Error while executing the `cleanup` hook:
dnsrobocert    | 2020-04-19 23:30:50 0f6824afd7a9 __main__[83] ERROR 403 Client Error: Forbidden for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.com&status=active
dnsrobocert    | Traceback (most recent call last):
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 48, in main
dnsrobocert    |     globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 125, in cleanup
dnsrobocert    |     _txt_challenge(profile, token, domain, action="delete")
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 174, in _txt_challenge
dnsrobocert    |     Client(lexicon_config).execute()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/client.py", line 77, in execute
dnsrobocert    |     self.provider.authenticate()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 69, in authenticate
dnsrobocert    |     return self._authenticate()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 32, in _authenticate
dnsrobocert    |     payload = self._get('/zones', {
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 142, in _get
dnsrobocert    |     return self._request('GET', url, query_params=query_params)
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/lexicon/providers/cloudflare.py", line 146, in _request
dnsrobocert    |     response.raise_for_status()
dnsrobocert    |   File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
dnsrobocert    |     raise HTTPError(http_error_msg, response=self)
dnsrobocert    | requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cloudflare.com/client/v4/zones?name=mydomain.com&status=active
dnsrobocert    | 
dnsrobocert    | Some challenges have failed.
dnsrobocert    | IMPORTANT NOTES:
dnsrobocert    |  - The following errors were reported by the server:
dnsrobocert    | 
dnsrobocert    |    Domain: api.mydomain.com
dnsrobocert    |    Type:   dns
dnsrobocert    |    Detail: DNS problem: NXDOMAIN looking up TXT for
dnsrobocert    |    _acme-challenge.api.mydomain.com - check that a DNS record
dnsrobocert    |    exists for this domain
dnsrobocert    | ----------
dnsrobocert    | 2020-04-19 23:30:50 0f6824afd7a9 dnsrobocert.core.main[1] ERROR An error occurred while processing certificate config `{'domains': ['api.mydomain.com'], 'profile': 'maestro_profile'}`:
dnsrobocert    | Command '['/usr/bin/python3', '-m', 'dnsrobocert.core.certbot', 'certonly', '-n', '--config-dir', '/etc/letsencrypt', '--work-dir', '/etc/letsencrypt/workdir', '--logs-dir', '/etc/letsencrypt/logs', '--manual', '--preferred-challenges=dns', '--manual-auth-hook', '/usr/bin/python3 -m dnsrobocert.core.hooks -t auth -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"', '--manual-cleanup-hook', '/usr/bin/python3 -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"', '--manual-public-ip-logging-ok', '--expand', '--deploy-hook', '/usr/bin/python3 -m dnsrobocert.core.hooks -t deploy -c "/tmp/tmprcwq5zn8/dnsrobocert-runtime.yml" -l "api.mydomain.com"', '--server', 'https://acme-staging-v02.api.letsencrypt.org/directory', '--cert-name', 'api.mydomain.com', '-d', 'api.mydomain.com']' returned non-zero exit status 1.
dnsrobocert    | 2020-04-19 23:30:50 0f6824afd7a9 dnsrobocert.core.main[1] INFO Revoke and delete certificates if needed
```

As you may notice, errors are like follow:

- `API Token`: `400 Client Error: Bad Request for url`
- `Global API KEY`: `403 Client Error: Forbidden for url`

I'm setting the variables directly in the `config.yml` as suggested in the [documentation](https://dnsrobocert.readthedocs.io/en/latest/user_guide.html#running-as-a-docker-container)

```yml
draft: false
acme:
  email_account: devops@mydomain.com
  staging: true
profiles:
  - name: maestro_profile
    provider: cloudflare
    provider_options:
      auth_username: devops@mydomain.com
      auth_token: <global_api_key|api_token>
certificates:
  - domains:
      - api.mydomain.com
    profile: maestro_profile
```

Do you have any suggestions I could follow? I already checked the issues on the other repositories but they are not merged yet.
